server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:    
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/depts/**
        filters:
         - name: CircuitBreaker
           args:
             name: DEPARTMENT-SERVICE
             fallbackuri: forward:/deptServiceFallBack
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
         - name: CircuitBreaker
           args:
             name: USER-SERVICE
             fallbackuri: forward:/userServiceFallBack        

hystrix:
  metrics:
    polling-interval-ms: 4000

management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream    

   